[project]
name = 'stacks_vibe_coding'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.bitcoin-dice]
path = 'contracts/bitcoin-dice.clar'
clarity_version = 3
epoch = 3.0
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
